leftnav:
- identifier: ce7bf71e-168b-967e-11be-61e5ffe31f5d
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 904853b8-4efe-d538-c9ff-e24733da330a
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 04064129-824e-a37f-053d-15c1788b5bf5
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: c32406dc-7a0a-88bc-244c-de436ae34539
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 8078623c-3779-9385-5a96-6ed40d24e942
  name: Projects
  pageRef: /pages/projects
  weight: 50
- identifier: 0570c265-b702-dfbc-1cfa-aea9eee79560
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
